[project]
id = "campaign-management"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.platform-api]
verify_jwt = false

[functions.tenant-api]
verify_jwt = false
